# state.py
from typing import TypedDict, Annotated, List, Optional
import operator

class UpworkAgentState(TypedDict):
    # The user's message/request
    input: str
    
    # Track the active "target" (Your profile or a competitor's)
    current_profile: Optional[dict]
    
    # A list of competitor profiles found during research
    # Annotated with operator.add so new data is appended, not overwritten
    competitors: Annotated[List[dict], operator.add]
    
    # The final analysis/strategy generated by the SEO Expert
    seo_strategy: str
    
    # Internal flag to tell the graph which node to go to next
    next_node: str
    
    # Questions the agent wants to ask the user
    questions: List[str]